### ISSUE TITLE
Learning Journal assignment references mismatched

### ISSUE THREAD

**Issue by BFriedland** [codefellows/python-dev-accelerator#9]
Several references to the previous, Flask-based version of the Learning Journal Part One assignment were not updated in [the new Pyramid version's Deploy to Heroku section](https://github.com/codefellows/python-dev-accelerator/blob/b72da07015643b59a941af1cb8121785d114ec70/source/assignments/day02/learning_journal_1.rst#deploy-to-heroku).

On lines 828 and 832, there are references to Flask being installed.

On lines 882, 887, and 895, there are references to a Heroku app and database which are different from the previous tutorial examples (ONYX versus RED and fizzy-fairy-1234 versus evening-brushlands-7955).

Also, the Learning Journal Part Three assignment's [Storing a User section](https://github.com/codefellows/python-dev-accelerator/blob/master/source/assignments/day04/learning_journal_3.rst#storing-a-user) has a typo on line 307. ("configuratin")

**Comment by BFriedland** [comment]
There are a few docstrings with style inconsistencies in the Learning Journal Part Two assignment. The most prominent example is the mixed capitalization in the docstring for the close_connection function in the [Releasing a Connection](https://github.com/codefellows/python-dev-accelerator/blob/master/source/assignments/day03/learning_journal_2.rst#releasing-a-connection) section.

**Comment by cewing** [comment]
Thanks @BFriedland, will work on fixing

**Comment by cewing** [comment]
the lj assignment has been completely rebuilt and so this issue is no longer relevant.  Thanks again for reporting.
